management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

server:
  error:
    include-stacktrace: never

spring:
  application:
    name: demo

aws:
  iam:
    user:
      accessKey:
        elapsedHours: 15000